### ISSUE TITLE
as jar depency

### ISSUE THREAD

**Issue by Miriam0** [PureGero/MultiLib#1]
Please, release it as jar. I can't use code because it throws errors

**Comment by BasToTheMax** [comment]
You can't use it as a standalone jar

**Comment by Miriam0** [comment]
But why? Release it as complete plugin for multipaper, bungee and velocity. I can't use that code because i have problems with maven and gradle. While im trying to copy&paste this code i gets errors that can't be resolved. Please release it as Plugins:(

**Comment by BasToTheMax** [comment]
Even if you could use this as a standalone plugin, it wouldn't do anything

**Comment by alaajel** [comment]
This is a library not a plugin, you should lookup

how dependencies  management work on both gradle/maven

**Comment by PureGero** [comment]
Will consider if PaperLib becomes a jar
